import React, { FC } from 'react';
import { Box, Flex, Heading, IconButton, Spacer, useColorMode, useColorModeValue } from '@chakra-ui/react';
import Head from 'next/head';
import { MoonIcon, SunIcon } from '@chakra-ui/icons';

interface LayoutProps {}

const Layout: FC<LayoutProps> = (props) => {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Flex h="64px" alignItems="center" p="2" mb="2px">
        <Box>
          <Heading size="md"></Heading>
        </Box>
        <Spacer />
        <Box>
          <IconButton
            variant="outline"
            colorScheme="teal"
            aria-label="Call Sage"
            fontSize="20px"
            onClick={toggleColorMode}
            icon={colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
          />
        </Box>
      </Flex>

      <main style={{ minHeight: 'calc(100vh-64px)' }}>{props.children}</main>
      <footer />
    </>
  );
};

export default Layout;
