import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button, Center, Container, HStack, IconButton, Stack, useColorMode, VStack } from '@chakra-ui/react';
import React, { useState } from 'react';
import Autocomplete from '../components/Autocomplete';
import { MoonIcon, PhoneIcon, RepeatIcon, SunIcon } from '@chakra-ui/icons';

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  const [isLoading, setLoading] = useState(false);
  const toggleLoading = () => {
    setLoading(!isLoading);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container h="30vh" w="50%" maxW="container.xs" alignItems="center" display="flex" pt={12}>
          <VStack w="100%" spacing={14}>
            <HStack w="100%">
              <IconButton
                variant="outline"
                colorScheme="teal"
                aria-label="Call Sage"
                fontSize="20px"
                onClick={toggleColorMode}
                icon={colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
              />
              <IconButton
                variant="outline"
                colorScheme="teal"
                aria-label="Call Sage"
                fontSize="20px"
                onClick={toggleLoading}
                icon={<RepeatIcon />}
              />
            </HStack>
            <VStack w="100%" spacing={0}>
              <Autocomplete
                isLoading={isLoading}
                suggestions={[
                  { label: 'lorem', key: 1 },
                  { label: 'ipsum', key: 2 },
                  { label: 'dolor', key: 3 },
                  { label: 'sit', key: 4 },
                ]}
                onSelect={(suggestion) => console.log('SUggestion:', suggestion)}
                isOpen
              />
              <span>lop</span>
            </VStack>
          </VStack>
        </Container>
      </main>

      <footer className={styles.footer} />
    </div>
  );
}
