import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Container, HStack, IconButton, useColorMode, VStack } from '@chakra-ui/react';
import React from 'react';
import { MoonIcon, SunIcon } from '@chakra-ui/icons';
import SearchBox from '../components/SearchBox';
import { Suggestion } from '../machines/searchBoxMachine';

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container h="100vh" w="100%" maxW="container.xs" display="flex" justifyContent="center" pt={12}>
          <VStack w="50%" spacing={14}>
            <HStack w="100%">
              <IconButton
                variant="outline"
                colorScheme="teal"
                aria-label="Call Sage"
                fontSize="20px"
                onClick={toggleColorMode}
                icon={colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
              />
            </HStack>
            <SearchBox fetchHandler={fetchPlaces} mapResultToSuggestion={fromPlaceToSuggestion} />
          </VStack>
        </Container>
      </main>

      <footer className={styles.footer} />
    </div>
  );
}

interface Place {
  place_id: number;
  licence: string;
  osm_type: string;
  osm_id: any;
  boundingbox: string[];
  lat: string;
  lon: string;
  display_name: string;
  class: string;
  type: string;
  importance: number;
  icon: string;
}

function fetchPlaces(query: string): Promise<Place[]> {
  return Boolean(query)
    ? fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${query.replaceAll(' ', '+')}`).then((response) =>
        response.json(),
      )
    : Promise.resolve([]);
}

function fromPlaceToSuggestion(place: Place): Suggestion {
  return {
    id: place.place_id,
    label: place.display_name,
  };
}
